/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package content;

import Ui.*;

import javax.swing.*;

/**
 * This class represents the Resources panel of the application.
 * It extends JPanel and is currently an empty form.
 * 
 * @author janna
 */
public class Resources extends javax.swing.JPanel {
    Icons a = new Icons();
    Illustrations b = new Illustrations();
    Learndesign c = new Learndesign();
    /**
     * Creates new form Resources
     * This constructor initializes the components of the Resources panel.
     */
    public Resources() {
        initComponents();
         main1.add(a);
         main1.add(b);
         main1.add(c);
        
         a.setVisible(false);
         b.setVisible(false);
         c.setVisible(false);
         toggleSkillButton2.doClick();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        main1 = new javax.swing.JPanel();
        toggleSkillButton2 = new content.ToggleSkillButton();
        toggleSkillButton3 = new content.ToggleSkillButton();
        toggleSkillButton4 = new content.ToggleSkillButton();

        setPreferredSize(new java.awt.Dimension(1257, 718));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(1497, 753));

        main1.setBackground(new java.awt.Color(0, 153, 204));
        main1.setLayout(new java.awt.CardLayout());

        buttonGroup1.add(toggleSkillButton2);
        toggleSkillButton2.setText("Icons");
        toggleSkillButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleSkillButton2MouseClicked(evt);
            }
        });

        buttonGroup1.add(toggleSkillButton3);
        toggleSkillButton3.setText("Illustrations");
        toggleSkillButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleSkillButton3MouseClicked(evt);
            }
        });

        buttonGroup1.add(toggleSkillButton4);
        toggleSkillButton4.setText("Designing Tools");
        toggleSkillButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleSkillButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(toggleSkillButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(toggleSkillButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(toggleSkillButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 996, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleSkillButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleSkillButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleSkillButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toggleSkillButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleSkillButton2MouseClicked
        if(toggleSkillButton2.isSelected())
        {
           a.setVisible(true);
           b.setVisible(false);
           c.setVisible(false);
         
           
        }  else if(toggleSkillButton4.isSelected()){
              a.setVisible(false);
           b.setVisible(false);
           c.setVisible(true);
           
        }    else if(toggleSkillButton3.isSelected()){
           a.setVisible(false);
           b.setVisible(true);
           c.setVisible(false);
          
        }         
    }//GEN-LAST:event_toggleSkillButton2MouseClicked

    private void toggleSkillButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleSkillButton4MouseClicked
        if(toggleSkillButton2.isSelected())
        {
           a.setVisible(true);
           b.setVisible(false);
           c.setVisible(false);
         
           
        }  else if(toggleSkillButton4.isSelected()){
              a.setVisible(false);
           b.setVisible(false);
           c.setVisible(true);
           
        }    else if(toggleSkillButton3.isSelected()){
           a.setVisible(false);
           b.setVisible(true);
           c.setVisible(false);
          
        }         
    }//GEN-LAST:event_toggleSkillButton4MouseClicked

    private void toggleSkillButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleSkillButton3MouseClicked
        if(toggleSkillButton2.isSelected())
        {
           a.setVisible(true);
           b.setVisible(false);
           c.setVisible(false);
         
           
        }  else if(toggleSkillButton4.isSelected()){
              a.setVisible(false);
           b.setVisible(false);
           c.setVisible(true);
           
        }    else if(toggleSkillButton3.isSelected()){
           a.setVisible(false);
           b.setVisible(true);
           c.setVisible(false);
          
        }         
    }//GEN-LAST:event_toggleSkillButton3MouseClicked

    /**
     * The main method to test the Resources panel by adding it to a JFrame.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the panel inside a JFrame */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Resources");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(900, 600);

                Resources resourcesPanel = new Resources();
                frame.setContentPane(resourcesPanel);

                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main1;
    private content.ToggleSkillButton toggleSkillButton2;
    private content.ToggleSkillButton toggleSkillButton3;
    private content.ToggleSkillButton toggleSkillButton4;
    // End of variables declaration//GEN-END:variables
}
